=== abtkod/database-capacity/test_data/books.dtd
<!-- version 1.0 -->

<!ELEMENT book (isbn, title, ean, binding, label, listprice, manufacturer, publisher, readinglevel, releasedate, publicationdate, studio, edition, dewey, numberofpages, dimensions, reviews, editorialreviews, images, creators, blurbers, dedications, epigraphs, firstwords, lastwords, quotations, series, awards, characters, places, subjects, tags, similarproducts, browseNodes)>
<!ELEMENT dimensions (height?, width?, length?, weight?)>
<!ELEMENT reviews (review*)>
<!ELEMENT review (authorid?, date, summary?, content?, rating, totalvotes, helpfulvotes)>
<!ELEMENT editorialreviews (editorialreview*)>
<!ELEMENT editorialreview (source, content?)>
<!ELEMENT images (image*)>
<!ELEMENT image (url, height?, width?, imageCategories)>
<!ELEMENT imageCategories (imagecategory*)>
<!ELEMENT creators (creator*)>
<!ELEMENT blurbers (blurber*)>
<!ELEMENT dedications (dedication*)>
<!ELEMENT epigraphs (epigraph*)>
<!ELEMENT firstwords (firstwordsitem*)>
<!ELEMENT lastwords (lastwordsitem*)>
<!ELEMENT quotations (quotation*)>
<!ELEMENT series (seriesitem*)>
<!ELEMENT awards (award*)>
<!ELEMENT browseNodes (browseNode*)>
<!ELEMENT characters (character*)>
<!ELEMENT places (place*)>
<!ELEMENT subjects (subject*)>
<!ELEMENT similarproducts (similarproduct*)>
<!ELEMENT tags (tag*)>

<!ELEMENT isbn (#PCDATA)>
<!ELEMENT ean (#PCDATA)>
<!ELEMENT binding (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT listprice (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT numberofpages (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT readinglevel (#PCDATA)>
<!ELEMENT releasedate (#PCDATA)>
<!ELEMENT publicationdate (#PCDATA)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT dewey (#PCDATA)>
<!ELEMENT creator (name, role)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT authorid (#PCDATA)>
<!ELEMENT totalvotes (#PCDATA)>
<!ELEMENT helpfulvotes (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT imagecategory (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT blurber (#PCDATA)>
<!ELEMENT dedication (#PCDATA)>
<!ELEMENT epigraph (#PCDATA)>
<!ELEMENT firstwordsitem (#PCDATA)>
<!ELEMENT lastwordsitem (#PCDATA)>
<!ELEMENT quotation (#PCDATA)>
<!ELEMENT seriesitem (#PCDATA)>
<!ELEMENT award (#PCDATA)>
<!ELEMENT browseNode (#PCDATA)>
<!ATTLIST browseNode id CDATA #REQUIRED>   
<!ELEMENT character (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT similarproduct (#PCDATA)>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag count CDATA #REQUIRED>

=== abtkod/database-capacity/test_data/1931243999.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- version 1.0 / 2009-11-07T14:59:40+01:00 --><!DOCTYPE book SYSTEM "books.dtd">
<book><isbn>1931243999</isbn><title>Journey Around My Room (Green Integer)</title><ean>9781931243995</ean><binding>Paperback</binding><label>Green Integer</label><listprice>$10.95</listprice><manufacturer>Green Integer</manufacturer><publisher>Green Integer</publisher><readinglevel/><releasedate/><publicationdate>2005-08-01</publicationdate><studio>Green Integer</studio><edition/><dewey>910</dewey><numberofpages>200</numberofpages><dimensions><height/><width/><length/><weight/></dimensions><reviews><review><authorid>A2OHN2IMZ7LSQ0</authorid><date>2008-01-04</date><summary>Interesting but not great.</summary><content>    I like this book, and it is interesting, but it's not worth the money.  I would recomend it if you got it from the library.  </content><rating>3</rating><totalvotes>7</totalvotes><helpfulvotes>1</helpfulvotes></review></reviews><editorialreviews><editorialreview><source>Product Description</source><content>&lt;p&gt;&lt;b&gt;Xavier de Maistre&lt;/b&gt; was born in Chambry, France, in 1763. Under house arrest for his participation in a duel, he wrote this remarkable fantasy, where for several days he makes an imaginary journey-around his room. He lived until 1852, writing several other books, most notably the sequel to this book, &lt;i&gt;Night Journey&lt;/i&gt;. His room travels have long been beloved by many readers and are here newly translated by Mark Axelrod, who teaches at Chapman University near Los Angeles.&lt;/p&gt;</content></editorialreview></editorialreviews><images><image><url>http://ecx.images-amazon.com/images/I/51aRar6TaHL._SL160_.jpg</url><height>160</height><width>114</width><imageCategories><imagecategory>primary</imagecategory></imageCategories></image><image><url>http://ecx.images-amazon.com/images/I/51aRar6TaHL._SL30_.jpg</url><height>30</height><width>21</width><imageCategories><imagecategory>primary</imagecategory></imageCategories></image><image><url>http://ecx.images-amazon.com/images/I/51aRar6TaHL._SL500_.jpg</url><height>500</height><width>355</width><imageCategories><imagecategory>primary</imagecategory></imageCategories></image><image><url>http://ecx.images-amazon.com/images/I/51aRar6TaHL._SL75_.jpg</url><height>75</height><width>53</width><imageCategories><imagecategory>primary</imagecategory></imageCategories></image></images><creators><creator><name>Mark Axelrod</name><role>Translator</role></creator><creator><name>Xavier de Maistre</name><role>Author</role></creator></creators><blurbers/><dedications/><epigraphs/><firstwords/><lastwords/><quotations/><series/><awards/><characters/><places/><subjects><subject>Relations with Authors, English</subject></subjects><tags><tag count="1">unread</tag><tag count="2">literature</tag><tag count="2">Fiction</tag></tags><similarproducts><similarproduct>0195101707</similarproduct><similarproduct>0375725342</similarproduct><similarproduct>0679779159</similarproduct><similarproduct>0679779175</similarproduct><similarproduct>1843911000</similarproduct></similarproducts><browseNodes><browseNode id="17">Literature &amp; Fiction</browseNode><browseNode id="27">Travel</browseNode><browseNode id="1000">Subjects</browseNode><browseNode id="10108">Essays</browseNode><browseNode id="10114">General</browseNode><browseNode id="10129">Contemporary</browseNode><browseNode id="283155">Books</browseNode><browseNode id="197498011">General</browseNode><browseNode id="388186011">Refinements</browseNode><browseNode id="394174011">Binding (binding)</browseNode><browseNode id="400272011">Paperback</browseNode><browseNode id="618072011">Format (feature_browse-bin)</browseNode><browseNode id="618083011">Printed Books</browseNode><browseNode id="713365011">General AAS</browseNode><browseNode id="713390011">General AAS</browseNode><browseNode id="713792011">General AAS</browseNode></browseNodes></book>
